import {StyleSheet} from "react-native";
import {rem,border,vh} from "css";
import {Colors} from "estate";


const colors=Colors.animation8;
const css={...StyleSheet.create({
    bandprober:{
        position:"absolute",
        width:"100%",
        height:18*rem,
        left:0,
        bottom:0,
        paddingBottom:1*rem,
        justifyContent:"flex-start",
        alignItems:"center",
        overflow:"hidden",
        //...border(1,"solid","white"),
    },
    row0:{
        width:"100%",
        flexDirection:"column",
        paddingRight:2*rem,
        paddingLeft:"15%",
        justifyContent:"space-between",
        alignItems:"flex-start",
        overflow:"hidden",
        //...border(1,"solid","white"),
    },
    row1:{
        width:"100%",
        display:"none",
        flex:1,
        justifyContent:"space-around",
        alignItems:"center",
        overflow:"hidden",
        //...border(1,"solid","white"),
    },
    row2:{
        width:"100%",
    },
    row3:{
        width:"100%",
        overflow:"scroll",
        //...border(1,"solid","white"),
    },
    row4:{
        width:"100%",
        paddingLeft:"15%",
    },
    label:{
        fontFamily:"cabin",
        fontSize:1.75*rem,
        textTransform:"capitalize",
        marginVertical:1*rem,
        opacity:0.5,
        color:colors.secondary,
    },
    overview:{
        fontSize:2*rem,
        opacity:1,
    },
    sectiontitle:{
        fontFamily:"squadaone",
        fontSize:2.5*rem,
        fontWeight:"600",
        color:colors.secondary,
        marginBottom:1.25*rem,
    },
    song:{
        width:"100%",
        flexDirection:"row",
        justifyContent:"space-around",
        alignItems:"center",
        marginVertical:1*rem,
    },
    songtitle:{
        flex:5,
        textTransform:"capitalize",
        fontWeight:"700",
        fontSize:1.5*rem,
        color:colors.text,
        opacity:0.85,
    },
    songduration:{
        flex:1,
        fontWeight:"700",
        fontSize:1.25*rem,
        color:colors.text,
        opacity:0.85,
    },
}),...{
    closebtn:{
        size:2*rem,
        color:colors.secondary,
        style:{
            marginTop:1*rem,
            marginLeft:"13%",
        },
    },
}};

export default css;